# Generated by Django 5.1.3 on 2024-12-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_plans', '0003_event_time_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
