# Generated by Django 5.1.3 on 2024-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_plans', '0006_event_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
